### PR TITLE
Add tty detection for MSYS terminals.

### LINKED ISSUE #10: tty detection for mintty
Over time, ripgrep has grown its own tty detection code which includes a hack for (seemingly reliably) detecting the presence of a tty on Windows inside mintty. Would you be interested in a PR that brings it to this crate?

There isn't much code, but you can see it all here: https://github.com/BurntSushi/ripgrep/blob/master/src/atty.rs

There is a pretty long issue on the topic of mintty detection here, which includes the provenance of the hack: https://github.com/BurntSushi/ripgrep/issues/94 --- Spoiler alert: [it's what `git` does](https://github.com/git/git/blob/master/compat/winansi.c#L558-L560).

### PR DESCRIPTION
**Pull request by BurntSushi**
This improves the tty detection in MSYS terminal environments on
Windows. Specifically, it uses heuristics to determine whether a
standard handle is a pipe or a tty.

Behavior in normal Windows consoles remains unchanged.

Fixes #10

### CODE REVIEW

**Comment by BurntSushi** [comment]
We should try to get #11 merged first. Once that's done, I'll rebase this PR. :-)

**Comment by BurntSushi** [comment]
@softprops Thanks! If CI passes, then I think this one should be good to go too. :-)

FWIW, I realize this implementation is a bit gnarly. I'd be happy to play unofficial maintainer. I'm watching this repo, so I'll keep an eye on it if any bugs crop up.

**Comment by BurntSushi** [comment]
@softprops Thanks! Sorry to be a bother, but could you also publish a new release too?

**Comment by softprops** [comment]
[done](https://crates.io/crates/atty)

**Pull request merged**
