### PR TITLE
Redox OS support

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by ids1024** [comment]
@softprops It would be great if you could merge this and https://github.com/softprops/termsize/pull/8.

**Comment by softprops** [comment]
will publish a new version as soon as I get some CI issues sorted out. looks like I've got a bit of travis debt to clean up

**Comment by ids1024** [comment]
@softprops Is Travis the only thing preventing a release? I'd like to be able to use this without cargo overrides.

Unit tests are a bit problematic, since you can't necessarily assume whether or not the tests will actually be run in a tty. I'm not sure there's a great solution to that.

**Comment by softprops** [comment]
@ids1024 yea agree I think part of this has to do with travis changing a base default image they use. I'm going to try and clean this up and rely on good faith to publish a new release and see if I can follow up with some flavor of integration style tests. You totally right that these tests are a bit fickle in that they rely on how the runtime runs the tests.

**Comment by softprops** [comment]
[done](https://crates.io/crates/atty). enjoy!

**Comment by ids1024** [comment]
Thanks! And could you also bump termsize? The CI there seems to be failing for similar reasons, i.e. some change in Travis (I guess it used to be attached to a pty, and isn't now, or something like that).

**Comment by softprops** [comment]
That's my guess as well. I'll try to get that done today

**Pull request merged**
