### PR TITLE
Updated winapi to 0.3

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by softprops** [comment]
I know less about the winapi but everything seems to check out here!

**Comment by alexbool** [comment]
Thanks!
FYI https://retep998.github.io/blog/winapi-0.3/

**Comment by alexbool** [comment]
@softprops would also be great to make a release with this

**Comment by softprops** [comment]
@alexbool done. released 0.2.6 with this change. https://crates.io/crates/atty

Thanks again for the patch!

**Pull request merged**
